# Generated by Django 4.1.5 on 2023-11-22 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
